# Generated by Django 2.1.5 on 2019-01-22 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailaddress', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=15)),
                ('notes', models.TextField()),
                ('attendancestatus', models.CharField(choices=[('A', 'ABSENT'), ('B', 'BOOKED'), ('C', 'CANCELLED'), ('D', 'ATTENDED')], default='B', max_length=1, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='CostCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, unique=True)),
                ('duration', models.FloatField(blank=True, default='1', null=True)),
                ('cost', models.FloatField(blank=True, default='0.00', null=True)),
                ('min_attendees', models.IntegerField(default=3)),
                ('max_attendees', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('reference', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanager.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('reference', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('starttime', models.TimeField()),
                ('status', models.CharField(choices=[('P', 'PROVISIONAL'), ('O', 'OPEN'), ('C', 'CLOSED'), ('X', 'CANCELLED'), ('D', 'DELIVERED'), ('-', 'COMPLETED')], default='P', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanager.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=80)),
                ('sortorder', models.IntegerField(default=1)),
                ('view', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ReportParameters_01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefrom', models.DateField()),
                ('dateto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailaddress', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('extension', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('room', models.CharField(max_length=50)),
                ('maxdelegates', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='presentation',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanager.Trainer'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanager.Venue'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanager.Presentation'),
        ),
    ]
